// <auto-generated />
using System;
using KIScheduler.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KIScheduler.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KischedulerDbContext))]
    partial class KischedulerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.ExecutionAttemptRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnostic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Effort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlatformProfileId", "PlatformId");

                    b.HasIndex("WorkItemId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("ExecutionAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExecutionAttempts_SequenceNumber", "SequenceNumber > 0");
                        });
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.ExecutionEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.HasIndex("PlatformProfileId");

                    b.HasIndex("WorkItemId", "OccurredAtUtc");

                    b.ToTable("ExecutionEvents", (string)null);
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.PlatformRow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Executable")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowUsageInStatusBar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Platforms", null, t =>
                        {
                            t.HasCheckConstraint("CK_Platforms_Capacity", "Capacity > 0");
                        });
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.PlatformProfileRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationDirectory")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowUsageInStatusBar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "PlatformId");

                    b.HasIndex("PlatformId")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = 1");

                    b.HasIndex("PlatformId", "ConfigurationDirectory")
                        .IsUnique();

                    b.HasIndex("PlatformId", "DisplayName")
                        .IsUnique();

                    b.HasIndex("PlatformId", "Name")
                        .IsUnique();

                    b.ToTable("PlatformProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlatformProfiles_DefaultName", "(IsDefault = 1 AND lower(Name) = 'default') OR (IsDefault = 0 AND lower(Name) <> 'default')");
                        });
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.PlatformUsageBlockRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseRule")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TriggeringAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TriggeringWorkItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TriggeringWorkItemId");

                    b.HasIndex("PlatformProfileId", "ReleasedAtUtc");

                    b.HasIndex("PlatformProfileId", "PlatformId");

                    b.ToTable("PlatformUsageBlocks", (string)null);
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.ProjectExecutionHoldRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseRule")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TriggeringWorkItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TriggeringWorkItemId");

                    b.HasIndex("ProjectId", "ReleasedAtUtc");

                    b.ToTable("ProjectExecutionHolds", (string)null);
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.ProjectRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTemplate")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationCommandsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RootPath")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.SchedulerLeaseRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("WorkItemId")
                        .IsUnique();

                    b.ToTable("SchedulerLeases", (string)null);
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.SettingRow", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.UsagePolicyRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysMask")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndSprintDurationTicks")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EndSprintMaxUsedPercent")
                        .HasColumnType("TEXT");

                    b.Property<long>("LocalEndTicks")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LocalStartTicks")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxUsedPercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("RefreshIntervalTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnknownUsageBehavior")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId", "ModelId");

                    b.ToTable("UsagePolicies", null, t =>
                        {
                            t.HasCheckConstraint("CK_UsagePolicies_MaxUsedPercent", "CAST(MaxUsedPercent AS REAL) >= 0 AND CAST(MaxUsedPercent AS REAL) <= 100");

                            t.HasCheckConstraint("CK_UsagePolicies_RefreshInterval", "RefreshIntervalTicks > 0");
                        });
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.UsageSnapshotRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ReadAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlatformProfileId", "ReadAtUtc");

                    b.HasIndex("PlatformProfileId", "PlatformId");

                    b.ToTable("UsageSnapshots", (string)null);
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.UsageWindowRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LimitId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LimitName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RateLimitReachedType")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReadAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResetAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UsedPercent")
                        .HasColumnType("TEXT");

                    b.Property<long?>("WindowDurationTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Name")
                        .IsUnique();

                    b.ToTable("UsageWindows", null, t =>
                        {
                            t.HasCheckConstraint("CK_UsageWindows_UsedPercent", "CAST(UsedPercent AS REAL) >= 0 AND CAST(UsedPercent AS REAL) <= 100");
                        });
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.WorkItemRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoCommit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommitMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Effort")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FirstAttemptStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasExecutionStarted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NormalRetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlatformId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("PlatformProfileId", "PlatformId");

                    b.HasIndex("Status", "Priority", "CreatedAtUtc");

                    b.ToTable("WorkItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_WorkItems_NormalRetryCount", "NormalRetryCount >= 0");

                            t.HasCheckConstraint("CK_WorkItems_Priority", "Priority >= 0 AND Priority <= 100");
                        });
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.ExecutionAttemptRow", b =>
                {
                    b.HasOne("KIScheduler.Infrastructure.Persistence.PlatformProfileRow", null)
                        .WithMany()
                        .HasForeignKey("PlatformProfileId", "PlatformId")
                        .HasPrincipalKey("Id", "PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KIScheduler.Infrastructure.Persistence.WorkItemRow", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.PlatformProfileRow", b =>
                {
                    b.HasOne("KIScheduler.Infrastructure.Persistence.PlatformRow", null)
                        .WithMany()
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.ExecutionEventRow", b =>
                {
                    b.HasOne("KIScheduler.Infrastructure.Persistence.ExecutionAttemptRow", null)
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KIScheduler.Infrastructure.Persistence.WorkItemRow", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.PlatformUsageBlockRow", b =>
                {
                    b.HasOne("KIScheduler.Infrastructure.Persistence.PlatformProfileRow", null)
                        .WithMany()
                        .HasForeignKey("PlatformProfileId", "PlatformId")
                        .HasPrincipalKey("Id", "PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KIScheduler.Infrastructure.Persistence.WorkItemRow", null)
                        .WithMany()
                        .HasForeignKey("TriggeringWorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.ProjectExecutionHoldRow", b =>
                {
                    b.HasOne("KIScheduler.Infrastructure.Persistence.ProjectRow", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KIScheduler.Infrastructure.Persistence.WorkItemRow", null)
                        .WithMany()
                        .HasForeignKey("TriggeringWorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.SchedulerLeaseRow", b =>
                {
                    b.HasOne("KIScheduler.Infrastructure.Persistence.WorkItemRow", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.UsageSnapshotRow", b =>
                {
                    b.HasOne("KIScheduler.Infrastructure.Persistence.PlatformProfileRow", null)
                        .WithMany()
                        .HasForeignKey("PlatformProfileId", "PlatformId")
                        .HasPrincipalKey("Id", "PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.UsageWindowRow", b =>
                {
                    b.HasOne("KIScheduler.Infrastructure.Persistence.UsageSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KIScheduler.Infrastructure.Persistence.WorkItemRow", b =>
                {
                    b.HasOne("KIScheduler.Infrastructure.Persistence.PlatformProfileRow", null)
                        .WithMany()
                        .HasForeignKey("PlatformProfileId", "PlatformId")
                        .HasPrincipalKey("Id", "PlatformId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KIScheduler.Infrastructure.Persistence.ProjectRow", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
